// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector_gen

import (
	"github.com/sebarthel/waypoint-handler/infrastructure/provider"
	"github.com/sebarthel/waypoint-handler/infrastructure/service"
)

// Injectors from injection.go:

func InitializeTaskScheduler() (service.TaskScheduler, error) {
	taskRepository, err := provider.ProvideTaskRepository()
	if err != nil {
		return service.TaskScheduler{}, err
	}
	taskScheduler, err := provider.ProvideTaskScheduler(taskRepository)
	if err != nil {
		return service.TaskScheduler{}, err
	}
	return taskScheduler, nil
}
