// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector_gen

import (
	"github.com/Journerist/drone-backend/infrastructure/provider"
	"github.com/Journerist/drone-backend/infrastructure/service"
)

// Injectors from injection.go:

func InitializeTaskScheduler() (*service.TaskScheduler, error) {
	droneTaskRepository, err := provider.ProvideDroneTaskRepository()
	if err != nil {
		return nil, err
	}
	taskScheduler, err := provider.ProvideTaskScheduler(droneTaskRepository)
	if err != nil {
		return nil, err
	}
	return taskScheduler, nil
}
